### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'int' and 'str'

### ISSUE THREAD

**Issue by EnSei1984** [maria-antoniak/little-mallet-wrapper#10]
Hey Maria and thanks for the Wrapper!

I've tried it for my (tiny) dataset and unfortunately got the following erros message:
```

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_7048/3888518702.py in <module>
----> 1 topic_keys, topic_distributions = lmw.quick_train_topic_model(path_to_mallet, 
      2                                                               num_topics,
      3                                                               output_directory_path,
      4                                                               training_data)

C:\ProgramData\Anaconda3\lib\site-packages\little_mallet_wrapper\little_mallet_wrapper.py in quick_train_topic_model(path_to_mallet, output_directory_path, num_topics, training_data)
     67                             training_data):
     68 
---> 69     path_to_training_data           = output_directory_path + '/training.txt'
     70     path_to_formatted_training_data = output_directory_path + '/mallet.training'
     71     path_to_model                   = output_directory_path + '/mallet.model.' + str(num_topics)

TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

Have you ever had this error message? What I've done wrong?
If you need further information, would you be so kind to tell me, please?

**Comment by maria-antoniak** [comment]
I haven't seen this particular error in this setting before, but it looks like something is going wrong with your `output_directory_path`. Can you show the code snippets where you define that variable and pass it into the `quick_train_topic_model` function?

**Comment by EnSei1984** [comment]
Dear Maria,

sure and thanks for giving attention to my issue!

```
os.environ["mallet_home"] = r'C:/Users/admin/.anaconda/navigator/gensim/mallet-2.0.8/'
path_to_mallet = 'C:\\Users\\admin\\.anaconda\\navigator\\gensim\\mallet-2.0.8\\bin\\mallet'
```

**Comment by maria-antoniak** [comment]
Hmm that's your MALLET path, but can you share the code where you define `output_directory_path` and pass it into the `quick_train_topic_model` function?

**Comment by EnSei1984** [comment]
Ohhh yes, sorry - it isn't my best day today. 

```
output_directory_path = r'C:/Users/admin/Desktop/ESMA/lmw-output'
```

```
topic_keys, topic_distributions = lmw.quick_train_topic_model(path_to_mallet, 
                                                              num_topics, 
                                                              output_directory_path, 
                                                              training_data)
```

as num_topics I choose 5, the MALLET path is defined as mentioned above and the training data consists of the corpus.

**Comment by maria-antoniak** [comment]
Aha! The order of arguments given to the function should be `quick_train_topic_model(path_to_mallet, output_directory_path, num_topics, training_data)`. You have `num_topics` in the wrong position, so the function thinks that `num_topics` is the output directory and then tries to concatenate an integer with a string, giving you the error message.
