### ISSUE TITLE
little_mallet_wrapper functions

### ISSUE THREAD

**Issue by nazifataha1** [maria-antoniak/little-mallet-wrapper#12]
Hi. I am trying to use your code source for my project and i am getting bunch of errors that are within the functions I checked the documentation which is helpful but I am getting internal error in the functions I am using on my list of strings aka training data. Is there a way to see how these functions are written so I can debug? Thank you

**Comment by maria-antoniak** [comment]
Hi, you can see all the code [here](https://github.com/maria-antoniak/little-mallet-wrapper/blob/master/little_mallet_wrapper/little_mallet_wrapper.py).

Generally, if you're getting a lot of errors, it indicates something wrong with MALLET or your MALLET path. Make sure you can run MALLET on the command line, as described [here](https://mimno.github.io/Mallet/topics).
