### ISSUE TITLE
how check wrapper's model convergence

### ISSUE THREAD

**Issue by findgit123** [maria-antoniak/little-mallet-wrapper#4]
@maria-antoniak,

Good jobs, Thank you for sharing.  Which command output the sampling convergence. How to determine it has converged during sampling for modeling. Can you let know how to check this measure?
.
Thanks.

**Comment by maria-antoniak** [comment]
The newest version (0.0.12) now prints the MALLET training output, which includes the log likelihood. I've updated the demo.ipynb to reflect this.

**Comment by findgit123** [comment]
@maria-antoniak, 
thank you so much for your reply. we found it is measure of log likelihood. How to interpret this measure? how to determine this sampling convergence? Can you let us know the relation between thiis log likelihood output and the convergence?
Thanks a million

**Comment by findgit123** [comment]
thanks a lot. Now I know how to get the measure. thank you
