### ISSUE TITLE
Is there a way to control for opening sentences?

### ISSUE THREAD

**Issue by zz2585** [maria-antoniak/little-mallet-wrapper#6]
Hi Maria,

Thanks for the amazing package! One quick question: I realize that there are opening sentences in the speech summaries I am about to train. For instance, every speech starts with 'Today, the speech topic is about ...'. So, topics that I am getting from the model are somehow affected by those clusters. I was curious if there is a way to control for those without removing them from the text completely. 

Any advice is appreciated! 

Thanks.

**Comment by maria-antoniak** [comment]
This is a great question! I already partially answered it on Twitter (https://twitter.com/maria_antoniak/status/1458489617964048387), but now that I hear a bit more detail, I think there are three options. First, you could just remove the opening sentences. Second, I always recommend removing duplicate documents during training, and if your "document" sizes aren't full speeches but rather sentences, this might also take care of the problem. Finally, if you have labels for these categories (e.g., speeches), you can use Laure Thompson's Authorless Topic Models package to downsample words associated with the categories before training: https://github.com/laurejt/authorless-tms

**Comment by zz2585** [comment]
Thanks Maria! I figured out how to incorporate Laure Thompson's Authorless Topic Models package, and made it work. I appreciate your time and have a nice one!
