### ISSUE TITLE
quick_train_topic_model issues

### ISSUE THREAD

**Issue by ccmilne** [maria-antoniak/little-mallet-wrapper#7]
Hello! I'm having some issues with the `quick_train_topic_model` function. Following the demo, I specified my output_directory_path as 'lmw-output' within the same directory as my Jupyter notebook. However, I'm getting an error that says `FileNotFoundError: [Errno 2] No such file or directory: 'lmw-output/mallet.topic_keys.20'`

The demo doesn't specify creating any directories or files before running the code. How can I address this issue?

Thanks,

**Comment by maria-antoniak** [comment]
Hi there! `quick_train_topic_model` runs a series of other functions that you would otherwise need to run manually. If those functions fail, then the whole thing fails, as each step relies on files created in the previous step. (Someday I'll add better error messages here; it's just a little tricky since some of these errors are coming from MALLET, and we would want to retrieve those errors both in the command line and in a notebook, and on both Windows and Mac.)

Some common errors for this function:
- The output directory path is incorrect (triple check!).
- You haven't installed MALLET. 
- You don't have your MALLET path set correctly.
- You don't have Java.

I would first check the output directory path and then check that you are able to run MALLET on the command line following MALLET's documentation: http://mallet.cs.umass.edu/quick-start.php

**Comment by siddharth-kale** [comment]
Hi Maria,

Thanks for the really cool wrapper. I'm getting the same error as @ccmilne . While the training.txt file is being created in the output folder without any issues, the topic keys file is not. I confirmed the checklist you mentioned above on my end and rest all looks fine. Still the error persists. 

Thanks,
Siddharth

> Hello! I'm having some issues with the `quick_train_topic_model` function. Following the demo, I specified my output_directory_path as 'lmw-output' within the same directory as my Jupyter notebook. However, I'm getting an error that says `FileNotFoundError: [Errno 2] No such file or directory: 'lmw-output/mallet.topic_keys.20'`
> 
> The demo doesn't specify creating any directories or files before running the code. How can I address this issue?
> 
> Thanks,

**Comment by maria-antoniak** [comment]
Hi Siddharth! That probably means that training is failing for some reason on your end. I would try using the individual functions `import_data()`, `train_topic_model()`, and `load_topic_keys()` to make sure this is the issue. If `train_topic_model()` is indeed the culprit, then you can try running the MALLET training yourself on the command line following [these instructions](https://mimno.github.io/Mallet/topics).

**Comment by dannylesmy** [comment]
You must define the environment variable that contains the source and not just the path to the binaries set
You can do it easily with os.environ
import os
os.environ["mallet_home"]=your path i.e. C:\\Mallet
mallet_path = "C:\\mallet\\bin\\mallet"

**Comment by smryd** [comment]
I am having the same issue cited by @ccmilne and @siddharth-kale above. I attempted to run the individual functions as advised by @maria-antoniak. I traced the issue, or at least one issue, back to `import_data()`. The function runs but yields a "NoneType" output. I am also seeing that training.txt is created but the formatted training file is not.

**Comment by maria-antoniak** [comment]
Hi @smryd! Probably something is going wrong with your connection to MALLET. Make sure you've specified your MALLET path, and then if it still isn't working, trying running MALLET from the command line to make sure everything is set up correctly: [https://mimno.github.io/Mallet/import](https://mimno.github.io/Mallet/import)

**Comment by smryd** [comment]
> Hi @smryd! Probably something is going wrong with your connection to MALLET. Make sure you've specified your MALLET path, and then if it still isn't working, trying running MALLET from the command line to make sure everything is set up correctly: https://mimno.github.io/Mallet/import

I was able to find the problem by running mallet on command line. The environment variable was set to \bin and not the overarching mallet folder. Everything is working now, thanks!

**Comment by Idalizette** [comment]
I am experiencing the same issue as the others in this thread. Mallet seems to work just fine in the command line, so I'm trying to do this:

> Hi Siddharth! That probably means that training is failing for some reason on your end. I would try using the individual functions `import_data()`, `train_topic_model()`, and `load_topic_keys()` to make sure this is the issue. If `train_topic_model()` is indeed the culprit, then you can try running the MALLET training yourself on the command line following [these instructions](https://mimno.github.io/Mallet/topics).

As far as I can tell, I got import_data() working, but I'm struggling with train_topic_model(). I'm understand I'm suppossed to input  lot of paths to where I want to store files and stuff. I want to store them all in the same directory, so I'm inputting the same path for most of these things, but that doesn't seem to work (I get "[last part of my path]""=="" was unexpected at this time.") So am I supposed to also include a name for the files or something? If so, with an extension? And if so, with what sort of extension?
