### ISSUE TITLE
Can I use the topic output in pyLDAvis?

### ISSUE THREAD

**Issue by Mathtype6** [maria-antoniak/little-mallet-wrapper#9]

**Comment by maria-antoniak** [comment]
The topic output from this package is the same output from [MALLET](https://mimno.github.io/Mallet/index). I don't think MALLET output is directly usable with pyLDAvis, but I also haven't used pyLDAvis in a long time.

For example, here is a post discussing how to convert MALLET files for use with pyLDAvis (but I think some of the Gensim code might be out of date):
https://medium.com/@jobethmuncy/formatting-pyldavis-and-mallet-model-7c0d00061b67
